import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {BookOpen,Building2,ChevronRight,FileText,Play,Receipt,RotateCcw,Settings2} from "lucide-react";
import "./styles.css";

const API="/api/v1";
const defaultBusiness={businessName:"HA-Corr Service Company",email:"billing@example.com",phone:"404-555-0100",licenseNumber:"",defaultCrewSize:2,unitPrices:{hourlyRate:95,materialCost:0,equipmentCost:0,disposalCost:0}};
const defaultStart={taxRate:8.9,discount:0,currency:"USD",paymentTerms:"Net 15"};

function Field({label,value,onChange,type="text",placeholder}){return <label className="field"><span>{label}</span><input type={type} value={value??""} placeholder={placeholder} onChange={e=>onChange(type==="number"?Number(e.target.value):e.target.value)}/></label>}
function App(){
 const [tab,setTab]=useState("workflow"),[categories,setCategories]=useState([]),[category,setCategory]=useState("");
 const [business,setBusiness]=useState(defaultBusiness),[settings,setSettings]=useState(defaultStart),[session,setSession]=useState(null),[answer,setAnswer]=useState(""),[invoice,setInvoice]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [apiKey,setApiKey]=useState(()=>localStorage.getItem("corrApiKey")||"");
 const [aiPrompt,setAiPrompt]=useState("");
 const [assistantMessage,setAssistantMessage]=useState("");
 useEffect(()=>{fetch(`${API}/guided/categories`).then(r=>r.json()).then(d=>{setCategories(d.categories||[]);}).catch(()=>setError("Unable to load categories."))},[]);
 const current=useMemo(()=>session?.nextQuestion,[session]);
 async function request(url,options={}){setBusy(true);setError("");try{localStorage.setItem("corrApiKey",apiKey);const r=await fetch(url,{headers:{"Content-Type":"application/json","X-API-Key":apiKey,...(options.headers||{})},...options});const d=await r.json();if(!r.ok)throw new Error(d.error||"Request failed");return d}catch(e){setError(e.message);throw e}finally{setBusy(false)}}
 async function start(){if(!apiKey){setError("Enter your client API key in Business Setup first.");return;}const d=await request(`${API}/ai/start`,{method:"POST",body:JSON.stringify({category:category||undefined,message:aiPrompt||`Start a ${category||"field service"} quote`,start:{...settings,businessSettings:business}})});setSession(d.workflow);setAssistantMessage(d.assistantMessage);setCategory(d.category);setInvoice(null);setAnswer("")}
 async function submitAnswer(){if(!current)return;let value=answer;if(current.type==="number"||current.type==="currency")value=Number(answer);if(current.type==="object"){try{value=JSON.parse(answer)}catch{setError("Enter valid JSON for the customer object.");return}}const d=await request(`${API}/ai/chat`,{method:"POST",body:JSON.stringify({sessionId:session.sessionId,action:"answer",value,message:String(answer)})});setSession(d.workflow);setAssistantMessage(d.assistantMessage);setAnswer("")}
 async function makeInvoice(){const d=await request(`${API}/ai/chat`,{method:"POST",body:JSON.stringify({sessionId:session.sessionId,action:"invoice",invoice:settings})});setInvoice(d.result);setAssistantMessage(d.assistantMessage);setSession(d.workflow)}
 function reset(){setSession(null);setInvoice(null);setAnswer("");setError("")}
 return <div className="shell"><aside><div className="brand"><Building2/><div><strong>HA-Corr</strong><small>Automation</small></div></div><nav>{[["workflow",Play,"Guided Quote"],["settings",Settings2,"Business Setup"],["docs",BookOpen,"Documentation"]].map(([id,Icon,label])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}><Icon size={18}/>{label}</button>)}</nav><div className="aside-note">One workflow from customer intake to detailed invoice.</div></aside><main><header><div><p className="eyebrow">MULTI-INDUSTRY OPERATIONS</p><h1>{tab==="workflow"?"Guided quote builder":tab==="settings"?"Business pricing setup":"API documentation"}</h1></div>{session&&<button className="ghost" onClick={reset}><RotateCcw size={16}/>New quote</button>}</header>{error&&<div className="error">{error}</div>}
 {tab==="workflow"&&<section>{!session?<div className="grid two"><div className="card hero"><span className="step">STEP 1</span><h2>Select a service category</h2><p>The workflow loads category-specific questions and calls the matching automation APIs as answers are provided.</p><Field label="Client API key" value={apiKey} onChange={setApiKey} placeholder="corr_..."/><label className="field"><span>Describe the job for AI</span><textarea rows="4" value={aiPrompt} onChange={e=>setAiPrompt(e.target.value)} placeholder="Example: The upstairs HVAC runs but does not cool."/></label><label className="field"><span>Category (optional override)</span><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">AI auto-detect</option>{categories.map(c=><option value={c.category} key={c.category}>{c.label}</option>)}</select></label><button className="primary" disabled={busy} onClick={start}>Start guided quote <ChevronRight size={18}/></button></div><div className="card summary"><h3>Current business defaults</h3><dl><div><dt>Business</dt><dd>{business.businessName}</dd></div><div><dt>Hourly rate</dt><dd>${business.unitPrices.hourlyRate}</dd></div><div><dt>Tax</dt><dd>{settings.taxRate}%</dd></div><div><dt>Terms</dt><dd>{settings.paymentTerms}</dd></div></dl><button className="link" onClick={()=>setTab("settings")}>Edit pricing and tax settings</button></div></div>:<div className="grid flow"><div className="card"><div className="progress"><span>{session.categoryLabel}</span><span>{Math.min(session.progress.currentIndex+1,session.progress.total)} / {session.progress.total}</span></div><div className="bar"><i style={{width:`${Math.min(100,(session.progress.currentIndex/session.progress.total)*100)}%`}}/></div>{assistantMessage&&<div className="assistant-message"><strong>AI Assistant</strong><p>{assistantMessage}</p></div>}{current?<><span className="step">NEXT QUESTION</span><h2>{current.question}</h2><QuestionInput question={current} value={answer} setValue={setAnswer}/><button className="primary" onClick={submitAnswer} disabled={busy||answer===""}>Save answer <ChevronRight size={18}/></button></>:<><span className="step success">READY</span><h2>All required information is collected.</h2><p>Review the accumulated answers and API calculations, then generate the invoice.</p><button className="primary" onClick={makeInvoice} disabled={busy}><Receipt size={18}/>Generate detailed invoice</button></>}</div><div className="card activity"><h3>Collected information</h3><pre>{JSON.stringify(session.answers,null,2)}</pre><h3>API calculations</h3><div className="chips">{session.apiResults?.map((x,i)=><span key={i}>{x.endpointType}</span>)}</div></div></div>}{invoice&&<Invoice invoice={invoice}/>}</section>}
 {tab==="settings"&&<section className="grid two"><div className="card"><h2>API access</h2><Field label="Client API key" value={apiKey} onChange={setApiKey} placeholder="Generate with npm run key:generate"/><p className="save-note">Sent as X-API-Key. The OpenAI key remains only on the server.</p><h2>Business identity</h2><Field label="Business name" value={business.businessName} onChange={v=>setBusiness({...business,businessName:v})}/><Field label="Billing email" value={business.email} onChange={v=>setBusiness({...business,email:v})}/><Field label="Phone" value={business.phone} onChange={v=>setBusiness({...business,phone:v})}/><Field label="License number" value={business.licenseNumber} onChange={v=>setBusiness({...business,licenseNumber:v})}/></div><div className="card"><h2>Pricing and invoice defaults</h2><Field label="Default hourly rate" type="number" value={business.unitPrices.hourlyRate} onChange={v=>setBusiness({...business,unitPrices:{...business.unitPrices,hourlyRate:v}})}/><Field label="Default crew size" type="number" value={business.defaultCrewSize} onChange={v=>setBusiness({...business,defaultCrewSize:v})}/><Field label="Tax rate (%)" type="number" value={settings.taxRate} onChange={v=>setSettings({...settings,taxRate:v})}/><Field label="Default discount" type="number" value={settings.discount} onChange={v=>setSettings({...settings,discount:v})}/><Field label="Payment terms" value={settings.paymentTerms} onChange={v=>setSettings({...settings,paymentTerms:v})}/><p className="save-note">These values are passed into every new guided session and invoice.</p></div></section>}
 {tab==="docs"&&<Docs/>}</main></div>}
function QuestionInput({question,value,setValue}){if(question.type==="select")return <label className="field"><span>Select one</span><select value={value} onChange={e=>setValue(e.target.value)}><option value="">Choose...</option>{question.options?.map(o=><option key={o}>{o}</option>)}</select></label>;if(question.type==="object")return <label className="field"><span>Customer JSON</span><textarea rows="7" value={value} onChange={e=>setValue(e.target.value)} placeholder={JSON.stringify(question.example||{name:"Customer Name",email:"customer@example.com"},null,2)}/></label>;return <Field label={question.required?"Required answer":"Optional answer"} type={question.type==="number"||question.type==="currency"?"number":question.type==="date"?"date":"text"} value={value} onChange={setValue} placeholder={question.example?.toString()}/>}
function Invoice({invoice}){return <div className="card invoice"><div className="invoice-head"><div><p className="eyebrow">DRAFT INVOICE</p><h2>{invoice.invoiceNumber}</h2></div><div className="total">${invoice.total.toFixed(2)}<small>{invoice.currency}</small></div></div><div className="invoice-meta"><span>{invoice.customer?.name}</span><span>{invoice.serviceAddress}</span><span>{invoice.paymentTerms}</span></div><table><thead><tr><th>Description</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody>{invoice.lineItems.map((x,i)=><tr key={i}><td>{x.description}<small>{x.sourceApi}</small></td><td>{x.quantity} {x.unit}</td><td>${Number(x.unitPrice).toFixed(2)}</td><td>${Number(x.amount).toFixed(2)}</td></tr>)}</tbody></table><div className="totals"><span>Subtotal <b>${invoice.subtotal.toFixed(2)}</b></span><span>Discount <b>-${invoice.discount.toFixed(2)}</b></span><span>Tax ({invoice.taxRate}%) <b>${invoice.tax.toFixed(2)}</b></span><strong>Total <b>${invoice.total.toFixed(2)}</b></strong></div><details><summary>Invoice JSON payload</summary><pre>{JSON.stringify(invoice,null,2)}</pre></details></div>}
function Docs(){return <section className="grid docs"><div className="card"><BookOpen/><h2>Interactive Swagger</h2><p>Browse every endpoint, required field, schema, and sample response.</p><a className="primary anchor" href="/docs" target="_blank">Open Swagger</a></div><div className="card"><FileText/><h2>Guided workflow</h2><code>POST /api/v1/ai/start</code><code>POST /api/v1/ai/chat</code><code>Header: X-API-Key</code><code>POST /api/v1/:category/start</code><code>POST /api/v1/:category/sessions/:id/answer</code><code>POST /api/v1/:category/sessions/:id/invoice</code></div><div className="card"><Play/><h2>Single-call quote</h2><code>POST /api/v1/guided/quote</code><pre>{`{
  "category":"hvac",
  "taxRate":8.9,
  "businessSettings":{"unitPrices":{"hourlyRate":125}},
  "answers":{"customer":{"name":"Acme"},"serviceAddress":"123 Main St", ...}
}`}</pre></div></section>}
createRoot(document.getElementById("root")).render(<App/>);
